apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: control-app
  labels:
    app: iot-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iot-demo
        name: control-app
    spec:
      containers:
        - name: control-app
          image: ppatierno/control-app:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: CONSUMER_GROUPID
              value: "control-app"
            - name: CONSUMER_TOPIC
              value: "iot-temperature-max"
            - name: CONSUMER_AUTO_OFFSET_RESET
              value: "earliest"
            - name: AMQP_SERVER
              value: "qdrouterd:5672"
            - name: AMQP_ADDRESS
              value: "control"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iot-demo
    name: control-app
  name: control-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: control-app
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: iot-demo
    name: control-app
  name: control-app
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: control-app