apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdrouterd
  labels:
    app: iot-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: qdrouterd
    spec:
      containers:
      - name: qdrouterd
        image: docker.io/ppatierno/qdrouterd:latest
        command: ["qdrouterd"]
        args: ["--config", "/etc/config/qdrouterd.conf"]
        volumeMounts:
          - name: qdrouterd-config
            mountPath: /etc/config
          - name: qdrouterd-certs
            mountPath: "/etc/qdrouterd-certs"
      volumes:
      - name: qdrouterd-config
        configMap:
          name: qdrouterd-config
      - name: qdrouterd-certs
        secret:
          secretName: qdrouterd-certs
        