apiVersion: v1
kind: Route
metadata:
  name: qdrouterd-route
  labels:
    app: iot-demo
spec:
  to:
    kind: Service
    name: qdrouterd
  port:
    targetPort: amqps
  tls:
    termination: passthrough 